events {}

http {

    upstream api_backend {
        server api:3000;
    }

    server {
        listen 80;

        location /api/ {
            proxy_pass http://api_backend/;
        }

        location /admin/ {
            proxy_pass http://admin:4000/;
        }
    }
}
