name: Infra Lab CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Validate Compose
        run: docker compose config

      - name: Build API Image
        run: docker build -t infra-lab-api ./api-server

      - name: Build Admin Image
        run: docker build -t infra-lab-admin ./admin-server
